#Declarations in config/settings.local.yml override those in config/settings.yml

session:
  # Name of cookie indicator is user signed in or not
  # Useful for serving cached pages for guest users
  logged_in_flag: _dpla_no_cache
  # Store settings. cookie_store and dalli_store are available
  store: cookie_store
  key: _dpla_frontend
  # Settings for memcache sessions
  dalli_store:
    memcache_server:
# User interface tweaks
ui:
  # Items
  items:
    # Default thumbnails for items without thumbnail
    # Mapping default thumbnails to sourceResource.type field
    # Text thumbnail will be displayed for unmatched types
    default_thumbnails:
      image:
        - image
      sound:
        - sound
      video:
  maps:
    center: [38, -93]
    zoom:
      start: 3
      min:  2
      max: 18
    grid_size:
      cols: 5
      rows: 3
    state_level: [4, 6]
    grid_level: [7, 18]
    page_size: 500
    popup_page_size: 50
